#Importing PyTorch

In [ ]:
import torch
torch.__version__

'2.10.0+cpu'

#Creating tensors

In [3]:
scaler = torch.tensor(5)
scaler

tensor(5)

In [4]:
#check the dimensions of a tensor using the ndim attribute.
scaler.ndim

0

In [5]:
#to retrieve the number from the tensor? use item() from python
scaler.item()

5

In [6]:
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [7]:
# Check the number of dimensions of vector
vector.ndim

1

In [8]:
#check shape of a vector
vector.shape

torch.Size([2])

In [9]:
MATRIX = torch.tensor([[7,7],
                      [5,5]])
MATRIX

tensor([[7, 7],
        [5, 5]])

In [10]:
MATRIX.ndim

2

In [11]:
MATRIX.shape

torch.Size([2, 2])

#How about we create a tensor?

In [12]:
TENSOR = torch.tensor([[[1,2,3],
                        [4,5,6],
                        [7,8,9]]])
TENSOR

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [13]:
TENSOR.ndim

3

In [18]:
TENSOR.shape
#That means there's 1 dimension of 3 by 3.

torch.Size([1, 3, 3])

In [20]:
import numpy as np
torch.tensor(np.array([[
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
]]))

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [21]:
torch.zeros([2,4], dtype=torch.int32)

tensor([[0, 0, 0, 0],
        [0, 0, 0, 0]], dtype=torch.int32)

In [22]:
torch.ones([2,4], dtype=torch.float)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.]])

##torch.device

In [23]:
device = torch.device('cuda:0' if torch.cuda.is_available() else 'cpu')
device

device(type='cpu')

##slicing

In [24]:
index = torch.tensor([
    [1,2,3],
    [4,5,6]
])
print(index[1][2])
print(index[0][0])

tensor(6)
tensor(1)


In [25]:
index[0][0]

tensor(1)

In [26]:
x = torch.tensor(2.5)
x.item()

2.5

#Random Tensors

In [15]:
random_tensor = torch.rand(size=(3,4))
random_tensor, random_tensor.dtype

(tensor([[0.5516, 0.3118, 0.2396, 0.2796],
         [0.0708, 0.6634, 0.9669, 0.1188],
         [0.0130, 0.5212, 0.8470, 0.5535]]),
 torch.float32)

In [17]:
range_0_10 = torch.arange(start=0, end=10, step=1)
range_0_10

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

#Tensor datatypes

In [28]:
float_32_tensor = torch.tensor([3.0,6.0,9.0],
                               dtype = None,
                               device = None,
                               requires_grad = False)
float_32_tensor.shape, float_32_tensor.dtype, float_32_tensor.device

(torch.Size([3]), torch.float32, device(type='cpu'))

# Manipulating tensors (tensor operations)

In [30]:
tensor = torch.tensor([1,2,3])
tensor

tensor([1, 2, 3])

In [31]:
tensor + 10

tensor([11, 12, 13])

In [32]:
tensor * 10

tensor([10, 20, 30])

Notice how the tensor values above didn't end up being tensor([110, 120, 130]), this is because the values inside the tensor don't change unless they're reassigned.

In [33]:
tensor

tensor([1, 2, 3])

Let's subtract a number and this time we'll reassign the tensor variable.

In [34]:
tensor = tensor - 10
tensor

tensor([-9, -8, -7])

In [35]:
tensor = tensor + 10
tensor

tensor([1, 2, 3])

Using torch functions

In [36]:
tensor.mul(tensor * 10)

tensor([10, 40, 90])

In [37]:
tensor

tensor([1, 2, 3])

However, it's more common to use the operator symbols like * instead of torch.mul()
## Element-wise multiplication

In [38]:
print(tensor, "*", tensor)
print("equals: ", tensor * tensor)

tensor([1, 2, 3]) * tensor([1, 2, 3])
equals:  tensor([1, 4, 9])


# Matrix multiplication

Let's create a tensor and perform element-wise multiplication and matrix multiplication on it.

In [39]:
tensor = torch.tensor([1,2,3])
tensor.shape

torch.Size([3])

In [40]:
# Element-wise matrix multiplication
tensor * tensor

tensor([1, 4, 9])

In [41]:
# Matrix multiplication
torch.matmul(tensor, tensor)

tensor(14)

In [42]:
# Can also use the "@" symbol for matrix multiplication, though not recommended
tensor @ tensor

tensor(14)

You can do matrix multiplication by hand but it's not recommended.

The in-built torch.matmul() method is faster.

In [45]:
%%time

value = 0
for i in range(len(tensor)):
  value += tensor[i] * tensor[i]
value

CPU times: user 2.84 ms, sys: 0 ns, total: 2.84 ms
Wall time: 3.73 ms


tensor(14)

#One of the most common errors in deep learning (shape errors)

In [46]:
tensor_A = torch.tensor([[1,2],
                         [3,4],
                         [5,6]],dtype = torch.float32)
tensor_B = torch.tensor([[7,8],
                         [9,10],
                         [11,12]],dtype = torch.float32)

In [48]:
print(tensor_A)
print(tensor_B)

tensor([[1., 2.],
        [3., 4.],
        [5., 6.]])
tensor([[ 7.,  8.],
        [ 9., 10.],
        [11., 12.]])


In [49]:
print(tensor_A)
print(tensor_B.T)

tensor([[1., 2.],
        [3., 4.],
        [5., 6.]])
tensor([[ 7.,  9., 11.],
        [ 8., 10., 12.]])


In [50]:
# The operation works when tensor_B is transposed
print(f"Original shapes: tensor_A = {tensor_A.shape}, tensor_B = {tensor_B.shape}\n")
print(f"New shapes: tensor_A = {tensor_A.shape} (same as above), tensor_B.T = {tensor_B.T.shape}\n")
print(f"Multiplying: {tensor_A.shape} * {tensor_B.T.shape} <- inner dimensions match\n")
print("Output:\n")
output = torch.matmul(tensor_A, tensor_B.T)
print(output)
print(f"\nOutput shape: {output.shape}")

Original shapes: tensor_A = torch.Size([3, 2]), tensor_B = torch.Size([3, 2])

New shapes: tensor_A = torch.Size([3, 2]) (same as above), tensor_B.T = torch.Size([2, 3])

Multiplying: torch.Size([3, 2]) * torch.Size([2, 3]) <- inner dimensions match

Output:

tensor([[ 23.,  29.,  35.],
        [ 53.,  67.,  81.],
        [ 83., 105., 127.]])

Output shape: torch.Size([3, 3])


In [51]:
torch.mm(tensor_A, tensor_B.T)

tensor([[ 23.,  29.,  35.],
        [ 53.,  67.,  81.],
        [ 83., 105., 127.]])

In [53]:
# Since the linear layer starts with a random weights matrix, let's make it reproducible (more on this later)
torch.manual_seed(42)
# This uses matrix multiplication
linear = torch.nn.Linear(in_features=2, # in_features = matches inner dimension of input
                         out_features=6) # out_features = describes outer value
x = tensor_A
output = linear(x)
print(f"Input shape: {x.shape}\n")
print(f"Output:\n{output}\n\nOutput shape: {output.shape}")

Input shape: torch.Size([3, 2])

Output:
tensor([[2.2368, 1.2292, 0.4714, 0.3864, 0.1309, 0.9838],
        [4.4919, 2.1970, 0.4469, 0.5285, 0.3401, 2.4777],
        [6.7469, 3.1648, 0.4224, 0.6705, 0.5493, 3.9716]],
       grad_fn=<AddmmBackward0>)

Output shape: torch.Size([3, 6])
