#Importing PyTorch

In [100]:
import torch
torch.__version__

'2.10.0+cpu'

#Creating tensors

In [101]:
scaler = torch.tensor(5)
scaler

tensor(5)

In [102]:
#check the dimensions of a tensor using the ndim attribute.
scaler.ndim

0

In [103]:
#to retrieve the number from the tensor? use item() from python
scaler.item()

5

In [104]:
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [105]:
# Check the number of dimensions of vector
vector.ndim

1

In [106]:
#check shape of a vector
vector.shape

torch.Size([2])

In [107]:
MATRIX = torch.tensor([[7,7],
                      [5,5]])
MATRIX

tensor([[7, 7],
        [5, 5]])

In [108]:
MATRIX.ndim

2

In [109]:
MATRIX.shape

torch.Size([2, 2])

#How about we create a tensor?

In [110]:
TENSOR = torch.tensor([[[1,2,3],
                        [4,5,6],
                        [7,8,9]]])
TENSOR

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [111]:
TENSOR.ndim

3

In [112]:
TENSOR.shape
#That means there's 1 dimension of 3 by 3.

torch.Size([1, 3, 3])

In [113]:
import numpy as np
torch.tensor(np.array([[
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
]]))

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [114]:
torch.zeros([2,4], dtype=torch.int32)

tensor([[0, 0, 0, 0],
        [0, 0, 0, 0]], dtype=torch.int32)

In [115]:
torch.ones([2,4], dtype=torch.float)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.]])

##torch.device

In [116]:
device = torch.device('cuda:0' if torch.cuda.is_available() else 'cpu')
device

device(type='cpu')

##slicing

In [117]:
index = torch.tensor([
    [1,2,3],
    [4,5,6]
])
print(index[1][2])
print(index[0][0])

tensor(6)
tensor(1)


In [118]:
index[0][0]

tensor(1)

In [119]:
x = torch.tensor(2.5)
x.item()

2.5

#Random Tensors

In [120]:
random_tensor = torch.rand(size=(3,4))
random_tensor, random_tensor.dtype

(tensor([[0.8694, 0.5677, 0.7411, 0.4294],
         [0.8854, 0.5739, 0.2666, 0.6274],
         [0.2696, 0.4414, 0.2969, 0.8317]]),
 torch.float32)

In [121]:
range_0_10 = torch.arange(start=0, end=10, step=1)
range_0_10

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

#Tensor datatypes

In [122]:
float_32_tensor = torch.tensor([3.0,6.0,9.0],
                               dtype = None,
                               device = None,
                               requires_grad = False)
float_32_tensor.shape, float_32_tensor.dtype, float_32_tensor.device

(torch.Size([3]), torch.float32, device(type='cpu'))

# Manipulating tensors (tensor operations)

In [123]:
tensor = torch.tensor([1,2,3])
tensor

tensor([1, 2, 3])

In [124]:
tensor + 10

tensor([11, 12, 13])

In [125]:
tensor * 10

tensor([10, 20, 30])

Notice how the tensor values above didn't end up being tensor([110, 120, 130]), this is because the values inside the tensor don't change unless they're reassigned.

In [126]:
tensor

tensor([1, 2, 3])

Let's subtract a number and this time we'll reassign the tensor variable.

In [127]:
tensor = tensor - 10
tensor

tensor([-9, -8, -7])

In [128]:
tensor = tensor + 10
tensor

tensor([1, 2, 3])

Using torch functions

In [129]:
tensor.mul(tensor * 10)

tensor([10, 40, 90])

In [130]:
tensor

tensor([1, 2, 3])

However, it's more common to use the operator symbols like * instead of torch.mul()
## Element-wise multiplication

In [131]:
print(tensor, "*", tensor)
print("equals: ", tensor * tensor)

tensor([1, 2, 3]) * tensor([1, 2, 3])
equals:  tensor([1, 4, 9])


# Matrix multiplication

Let's create a tensor and perform element-wise multiplication and matrix multiplication on it.

In [132]:
tensor = torch.tensor([1,2,3])
tensor.shape

torch.Size([3])

In [133]:
# Element-wise matrix multiplication
tensor * tensor

tensor([1, 4, 9])

In [134]:
# Matrix multiplication
torch.matmul(tensor, tensor)

tensor(14)

In [135]:
# Can also use the "@" symbol for matrix multiplication, though not recommended
tensor @ tensor

tensor(14)

You can do matrix multiplication by hand but it's not recommended.

The in-built torch.matmul() method is faster.

In [136]:
%%time

value = 0
for i in range(len(tensor)):
  value += tensor[i] * tensor[i]
value

CPU times: user 752 µs, sys: 0 ns, total: 752 µs
Wall time: 1.11 ms


tensor(14)

#One of the most common errors in deep learning (shape errors)

In [137]:
tensor_A = torch.tensor([[1,2],
                         [3,4],
                         [5,6]],dtype = torch.float32)
tensor_B = torch.tensor([[7,8],
                         [9,10],
                         [11,12]],dtype = torch.float32)

In [138]:
print(tensor_A)
print(tensor_B)

tensor([[1., 2.],
        [3., 4.],
        [5., 6.]])
tensor([[ 7.,  8.],
        [ 9., 10.],
        [11., 12.]])


In [139]:
print(tensor_A)
print(tensor_B.T)

tensor([[1., 2.],
        [3., 4.],
        [5., 6.]])
tensor([[ 7.,  9., 11.],
        [ 8., 10., 12.]])


In [140]:
# The operation works when tensor_B is transposed
print(f"Original shapes: tensor_A = {tensor_A.shape}, tensor_B = {tensor_B.shape}\n")
print(f"New shapes: tensor_A = {tensor_A.shape} (same as above), tensor_B.T = {tensor_B.T.shape}\n")
print(f"Multiplying: {tensor_A.shape} * {tensor_B.T.shape} <- inner dimensions match\n")
print("Output:\n")
output = torch.matmul(tensor_A, tensor_B.T)
print(output)
print(f"\nOutput shape: {output.shape}")

Original shapes: tensor_A = torch.Size([3, 2]), tensor_B = torch.Size([3, 2])

New shapes: tensor_A = torch.Size([3, 2]) (same as above), tensor_B.T = torch.Size([2, 3])

Multiplying: torch.Size([3, 2]) * torch.Size([2, 3]) <- inner dimensions match

Output:

tensor([[ 23.,  29.,  35.],
        [ 53.,  67.,  81.],
        [ 83., 105., 127.]])

Output shape: torch.Size([3, 3])


In [141]:
torch.mm(tensor_A, tensor_B.T)

tensor([[ 23.,  29.,  35.],
        [ 53.,  67.,  81.],
        [ 83., 105., 127.]])

In [142]:
# Since the linear layer starts with a random weights matrix, let's make it reproducible (more on this later)
torch.manual_seed(42)
# This uses matrix multiplication
linear = torch.nn.Linear(in_features=2, # in_features = matches inner dimension of input
                         out_features=6) # out_features = describes outer value
x = tensor_A
output = linear(x)
print(f"Input shape: {x.shape}\n")
print(f"Output:\n{output}\n\nOutput shape: {output.shape}")

Input shape: torch.Size([3, 2])

Output:
tensor([[2.2368, 1.2292, 0.4714, 0.3864, 0.1309, 0.9838],
        [4.4919, 2.1970, 0.4469, 0.5285, 0.3401, 2.4777],
        [6.7469, 3.1648, 0.4224, 0.6705, 0.5493, 3.9716]],
       grad_fn=<AddmmBackward0>)

Output shape: torch.Size([3, 6])


#Finding the min, max, mean, sum, etc (aggregation)

In [143]:
x = torch.arange(0, 100, 10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [144]:
x.min(), x.max(), x.sum()

(tensor(0), tensor(90), tensor(450))

In [145]:
x.type(torch.float32).mean()

tensor(45.)

In [146]:
x.argmin(), x.argmax()

(tensor(0), tensor(9))

In [147]:
# Create a tensor and check its datatype
tensor = torch.arange(10., 100., 10.)
tensor.dtype

torch.float32

In [148]:
# Create an int8 tensor
tensor_int16 = tensor.type(torch.int16)
tensor_int16

tensor([10, 20, 30, 40, 50, 60, 70, 80, 90], dtype=torch.int16)

In [149]:
# Create an int8 tensor
tensor_int8 = tensor.type(torch.int8)
tensor_int8

tensor([10, 20, 30, 40, 50, 60, 70, 80, 90], dtype=torch.int8)

#Reshaping, stacking, squeezing and unsqueezing

In [150]:
y = torch.arange(1,7)
y, y.shape

(tensor([1, 2, 3, 4, 5, 6]), torch.Size([6]))

Now let's add an extra dimension with torch.reshape().

In [151]:
y_reshaped = y.reshape(1,6)
y, y.shape, y_reshaped, y_reshaped.shape

(tensor([1, 2, 3, 4, 5, 6]),
 torch.Size([6]),
 tensor([[1, 2, 3, 4, 5, 6]]),
 torch.Size([1, 6]))

modify the view, original tensor also changes
why?
Because both point to same memory.

In [152]:
z = y.view(2,3)
z

tensor([[1, 2, 3],
        [4, 5, 6]])

modify the view

In [153]:
z[0][0] = 99
z

tensor([[99,  2,  3],
        [ 4,  5,  6]])

original tensor also changes
why?
Because both point to same memory.

In [154]:
y

tensor([99,  2,  3,  4,  5,  6])

In [155]:
# Stack tensors on top of each other
y_stacked = torch.stack([y, y, y, y], dim=0) # try changing dim to dim=1 and see what happens
y_stacked

tensor([[99,  2,  3,  4,  5,  6],
        [99,  2,  3,  4,  5,  6],
        [99,  2,  3,  4,  5,  6],
        [99,  2,  3,  4,  5,  6]])

In [156]:
print(f"Previous tensor: {y_reshaped}")
print(f"Previous shape: {y_reshaped.shape}")

# Remove extra dimension from x_reshaped
y_squeezed = y_reshaped.squeeze()
print(f"\nNew tensor: {y_squeezed}")
print(f"New shape: {y_squeezed.shape}")

Previous tensor: tensor([[99,  2,  3,  4,  5,  6]])
Previous shape: torch.Size([1, 6])

New tensor: tensor([99,  2,  3,  4,  5,  6])
New shape: torch.Size([6])


In [157]:
print(f"Previous tensor: {y_squeezed}")
print(f"Previous shape: {y_squeezed.shape}")

## Add an extra dimension with unsqueeze
y_unsqueezed = y_squeezed.unsqueeze(dim=0)
print(f"\nNew tensor: {y_unsqueezed}")
print(f"New shape: {y_unsqueezed.shape}")

Previous tensor: tensor([99,  2,  3,  4,  5,  6])
Previous shape: torch.Size([6])

New tensor: tensor([[99,  2,  3,  4,  5,  6]])
New shape: torch.Size([1, 6])


In [158]:
# Create tensor with specific shape
x_original = torch.rand(size=(224, 224, 3))

# Permute the original tensor to rearrange the axis order
x_permuted = x_original.permute(2, 0, 1) # shifts axis 0->1, 1->2, 2->0

print(f"Previous shape: {x_original.shape}")
print(f"New shape: {x_permuted.shape}")

Previous shape: torch.Size([224, 224, 3])
New shape: torch.Size([3, 224, 224])


Because permuting returns a view (shares the same data as the original), the values in the permuted tensor will be the same as the original tensor and if you change the values in the view, it will change the values of the original.

#Indexing (selecting data from tensors)

In [159]:
x = torch.arange(1, 10).reshape(1, 3, 3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [160]:
# Let's index bracket by bracket
print(f"First square bracket:\n{x[0]}")
print(f"Second square bracket: {x[0][0]}")
print(f"Third square bracket: {x[0][0][0]}")

First square bracket:
tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
Second square bracket: tensor([1, 2, 3])
Third square bracket: 1


In [161]:
x[:, 0]

tensor([[1, 2, 3]])

In [162]:
x[:, :, 1]

tensor([[2, 5, 8]])

In [163]:
x[:, 1, 1]

tensor([5])

In [164]:
x[0, 0, :] # same as x[0][0]

tensor([1, 2, 3])

# PyTorch tensors & NumPy

##NumPy Array → PyTorch Tensor

In [165]:
array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array)
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

torch.from_numpy() usually shares memory with NumPy array.

That means:

changing one can affect the other

BUT in your example:


In [166]:
array = array + 1

does NOT modify original array in-place.

In [167]:
array, tensor

(array([2., 3., 4., 5., 6., 7., 8.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

##in-place modification

In [168]:
array = np.array([1.,2.,3.])
tensor = torch.from_numpy(array)
array += 1

This WOULD affect tensor too.

Because memory is shared.

In [169]:
array, tensor

(array([2., 3., 4.]), tensor([2., 3., 4.], dtype=torch.float64))

##Tensor → NumPy Array

In [170]:
tensor = torch.ones(7)

numpy_tensor = tensor.numpy()
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

Tensor and NumPy array usually share memory.

BUT your example:

In [171]:
tensor = tensor + 1

creates a NEW tensor.

So NumPy array still points to old memory.

In [172]:
tensor, numpy_tensor

(tensor([2., 2., 2., 2., 2., 2., 2.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

inplace same as above

#Reproducibility (trying to take the random out of random)

In [173]:
random_tensor_A = torch.rand(3, 4)
random_tensor_B = torch.rand(3, 4)

random_tensor_A, random_tensor_B

(tensor([[0.8016, 0.3649, 0.6286, 0.9663],
         [0.7687, 0.4566, 0.5745, 0.9200],
         [0.3230, 0.8613, 0.0919, 0.3102]]),
 tensor([[0.9536, 0.6002, 0.0351, 0.6826],
         [0.3743, 0.5220, 0.1336, 0.9666],
         [0.9754, 0.8474, 0.8988, 0.1105]]))

In [174]:
print(f"Does Tensor A equal Tensor B? (anywhere)")
random_tensor_A == random_tensor_B

Does Tensor A equal Tensor B? (anywhere)


tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])

That's where torch.manual_seed(seed) comes in, where seed is an integer (like 42 but it could be anything) that flavours the randomness.

In [99]:
import random

RANDOM_SEED=42
torch.manual_seed(seed=RANDOM_SEED)
random_tensor_C = torch.rand(3, 4)

torch.random.manual_seed(seed=RANDOM_SEED)
random_tensor_D = torch.rand(3, 4)

print(f"Tensor C:\n{random_tensor_C}\n")
print(f"Tensor D:\n{random_tensor_D}\n")
print(f"Does Tensor C equal Tensor D? (anywhere)")
random_tensor_C == random_tensor_D

Tensor C:
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])

Tensor D:
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])

Does Tensor C equal Tensor D? (anywhere)


tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])